/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SpSideDrawer {
    'open': boolean;
    'openIt': () => Promise<void>;
    'title': string;
  }
  interface SpStockPrice {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSpSideDrawerElement extends Components.SpSideDrawer, HTMLStencilElement {}
  var HTMLSpSideDrawerElement: {
    prototype: HTMLSpSideDrawerElement;
    new (): HTMLSpSideDrawerElement;
  };

  interface HTMLSpStockPriceElement extends Components.SpStockPrice, HTMLStencilElement {}
  var HTMLSpStockPriceElement: {
    prototype: HTMLSpStockPriceElement;
    new (): HTMLSpStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'sp-side-drawer': HTMLSpSideDrawerElement;
    'sp-stock-price': HTMLSpStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface SpSideDrawer extends JSXBase.HTMLAttributes<HTMLSpSideDrawerElement> {
    'open'?: boolean;
    'title'?: string;
  }
  interface SpStockPrice extends JSXBase.HTMLAttributes<HTMLSpStockPriceElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'sp-side-drawer': SpSideDrawer;
    'sp-stock-price': SpStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


